[".scripts/bin/rmtrash"]
    type = "git-repo"
    url = "https://github.com/PhrozenByte/rmtrash.git"
    refreshPeriod = "168h"

[".scripts/bin/with"]
    type = "git-repo"
    url = "https://github.com/mchav/with.git"
    refreshPeriod = "168h"
