[".scripts/bin/rmtrash"]
    type = "git-repo"
    url = "https://github.com/PhrozenByte/rmtrash.git"
    refreshPeriod = "168h"

[".scripts/bin/trash-cli"]
    type = "git-repo"
    url = "https://github.com/andreafrancia/trash-cli.git"
    refreshPeriod = "168h"

