[".scripts/bin/rmtrash"]
    type = "git-repo"
    url = "https://github.com/PhrozenByte/rmtrash.git"
    refreshPeriod = "168h"

[".scripts/bin/with"]
    type = "git-repo"
    url = "https://github.com/mchav/with.git"
    refreshPeriod = "168h"

[".scripts/other/wolfram"]
    type = "git-repo"
    url = "https://github.com/WolframResearch/WolframLanguageForJupyter.git"
    refreshPeriod = "168h"

[".scripts/other/nightdrive"]
    type = "git-repo"
    url = "https://github.com/guttyar-2213/nightdrive.git"
    refreshPeriod = "168h"
